# Generated by Django 4.2.4 on 2023-12-05 04:38

import appname.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_personelturu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('unvan', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(default='images/defaultprofilephoto.jpg', upload_to=appname.models.personel_fotograf_path)),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('personel_turu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.personelturu')),
            ],
        ),
    ]
