# Generated by Django 4.2.4 on 2023-12-05 04:46

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_alter_persons_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='img',
            field=models.ImageField(default='defaults/defaultprofilephoto.jpeg', upload_to=appname.models.personel_fotograf_path),
        ),
    ]
