# Generated by Django 4.2.4 on 2023-12-07 20:53

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_alter_persons_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brosurler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField()),
                ('kapak_fotografi', models.ImageField(default='defaults/defaultprofilephoto.jpeg', upload_to=appname.models.kapakfoto_path)),
                ('pdf_dosya', models.FileField(upload_to=appname.models.pdf_dosya_path)),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
    ]
