# Generated by Django 4.2.4 on 2023-12-07 22:58

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_brosurler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brosurler',
            name='kapak_fotografi',
            field=models.ImageField(upload_to=appname.models.kapakfoto_path),
        ),
    ]
