# Generated by Django 4.2.4 on 2023-12-10 08:05

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_alter_brosurler_kapak_fotografi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brosurler',
            name='kapak_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path),
        ),
        migrations.AlterField(
            model_name='brosurler',
            name='pdf_dosya',
            field=models.FileField(blank=True, null=True, upload_to=appname.models.pdf_dosya_path),
        ),
    ]
