# Generated by Django 4.2.4 on 2023-12-12 11:33

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0014_gorselbasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamuoyuDuyurulari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField()),
                ('kapak_fotografi', models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_kamuoyuduyurulari)),
                ('tarih', models.DateField()),
                ('durum', models.BooleanField(default=True)),
                ('icerik', models.TextField()),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
    ]
