# Generated by Django 4.2.4 on 2023-12-16 02:25

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0018_mushaffarklari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushaffarklari',
            name='pdf_dosya',
        ),
        migrations.AlterField(
            model_name='mushaffarklari',
            name='kapak_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_kitapkategori),
        ),
    ]
