# Generated by Django 4.2.4 on 2023-12-16 02:26

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0019_remove_mushaffarklari_pdf_dosya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitapKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField()),
                ('kapak_fotografi', models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_kitapkategori)),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='mushaffarklari',
            name='pdf_dosya',
            field=models.FileField(blank=True, null=True, upload_to=appname.models.pdf_dosya_path_mushaffarklari),
        ),
        migrations.AlterField(
            model_name='mushaffarklari',
            name='kapak_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_mushaffarklari),
        ),
    ]
