# Generated by Django 4.2.4 on 2023-12-17 11:37

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0021_kitap'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGaleriKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('kapak_fotografi', models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_videogalerikategori)),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
    ]
