# Generated by Django 4.2.4 on 2023-12-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0023_videogaleri01'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
