# Generated by Django 4.2.4 on 2023-12-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0025_kamuoyuduyurulari_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogaleri01',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
