# Generated by Django 4.2.4 on 2023-12-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0026_videogaleri01_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogaleri01',
            name='slug',
        ),
    ]
