# Generated by Django 4.2.4 on 2023-12-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0027_remove_videogaleri01_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogalerikategori',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
