# Generated by Django 4.2.4 on 2023-12-24 11:28

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0032_sempozyumlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogaleri01',
            name='kapak_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_videogaleri),
        ),
    ]
