# Generated by Django 4.2.4 on 2023-12-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0035_egitimler'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitimler',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
