# Generated by Django 4.2.4 on 2023-12-26 22:08

import appname.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0036_egitimler_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konferanslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('tarih', models.DateField()),
                ('egitmen', models.CharField(max_length=200)),
                ('kapak_fotografi', models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_egitimler)),
                ('icerik', models.TextField()),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.fotogaleri')),
                ('yayin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.videogaleri01')),
            ],
        ),
    ]
