# Generated by Django 4.2.4 on 2023-12-27 23:33

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0039_arastirmalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to=appname.models.slider_path)),
                ('url', models.URLField(max_length=500)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
