# Generated by Django 4.2.4 on 2023-12-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0040_sliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='durum',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sliders',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
