# Generated by Django 4.2.4 on 2023-12-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0041_sliders_durum_sliders_is_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliders',
            name='is_published',
        ),
    ]
