# Generated by Django 4.2.4 on 2023-12-28 04:17

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0042_remove_sliders_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_puppup)),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='brosurler',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bultenler',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gorselbasin',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kamuoyuduyurulari',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kitapkategori',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mushaffarklari',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='temelkavramlar',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='temelkonular',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='yayinlarimizdansecmeler',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='yazilibasin',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
    ]
