# Generated by Django 4.2.4 on 2023-12-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0043_puppup_alter_brosurler_baslik_alter_bultenler_baslik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puppup',
            old_name='baslik',
            new_name='name',
        ),
    ]
