# Generated by Django 4.2.4 on 2024-01-03 10:29

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0045_rename_is_disabled_menuitem_is_removed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalikGorsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to=appname.models.kapakfoto_path_baslikgorsel)),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
    ]
