# Generated by Django 4.2.4 on 2024-01-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0046_balikgorsel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
    ]
