# Generated by Django 4.2.4 on 2024-01-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0048_ebulten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebulten',
            old_name='album',
            new_name='bulten',
        ),
    ]
