# Generated by Django 4.2.4 on 2024-01-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0049_rename_album_ebulten_bulten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebulten',
            name='durum',
        ),
    ]
