# Generated by Django 4.2.4 on 2024-01-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0050_remove_ebulten_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='order',
            field=models.IntegerField(default=67),
            preserve_default=False,
        ),
    ]
